version: 3.0.0

services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - redirects_api:/var/lib/postgresql/data
  
  api:
    build: ../src/.
    env_file:
      - .env
    volumes:
      - ../src:/app
    depends_on:
      - db
    command: ["/wait-for-it.sh", "db:5432", "--", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0"]
    ports:
      - "8000:8000"

volumes:
  redirects_api: